### PR TITLE
fix os path join to allow the game to work properly on all platforms

### PR DESCRIPTION
**Pull request by Arrowana**

### CODE REVIEW

**Comment by amarlearning** [comment]
hey @Arrowana 
Have you tested it on *nix based systems? because I am getting an error!
screenshot from 2016-10-30 12-58-48

**Comment by Arrowana** [comment]
Yes that's the point, this branch is fixing the issue. You screenshot reveals that you are not running this branch

**Comment by amarlearning** [comment]
@Arrowana can you please resolve this conflict, so that i can easiely merge the request!

**Comment by amarlearning** [comment]
@Arrowana If you are facing any problem in resolving the conflicts, feel free to ask!

**Comment by Arrowana** [comment]
You already merged my changes so there is nothing to merge

**Comment by amarlearning** [comment]
@Arrowana Yeah, I tried to merge your change. But still, there is a conflict because of which of which I am not able to merge!

**Pull request closed without merging**
